### ISSUE TITLE
What data was used to train the pretrained vallex?

### ISSUE THREAD

**Issue by EsOff** [ddlBoJack/SLAM-LLM#80]
This open source project is fantastic. Is it convenient to inform which data was used to train vallex?

**Comment by wangtianrui** [comment]
We trained vallex 1 epoch on MLS (40000H English) and Wenetspeech (10000H Chinese).

**Comment by lancelee98** [comment]
> We trained vallex 1 epoch on MLS (40000H English) and Wenetspeech (10000H Chinese).

I find the quality of the generated audio is unstable.
Sometimes , the result is good enough, but sometimes the result is fully wrong, or missing some words.
I guess the reason is the wenetspeech label is not exactly the same as the audio content.
By the way, how many hours did you train? and how much GPU memory didi you used?

**Comment by wangtianrui** [comment]
Yes, as you mentioned, the speech quality of wenetspeech is poor. Improving the accuracy of the transcription and the quality of speech would achieve better performance.

We trained VALLEX (AR+NAR) on 2xA100-80G for 3.5 days (AR) and 3 days (NAR).
